# Database credentials
database_dev:
  host: "40.76.139.118"
  port: "27018"
  user: "neo"
  pass: "pIqGZYY"
  dbname: "neo2"
  database: "neo2"

#database_test:
#  host: "s-uf63bd0cc5896674-pub.mongodb.rds.aliyuncs.com"
#  port: "3717"
#  user: "Vincent"
#  pass: "QMRhLk9m8rqXWC3X9pMJ"
#  dbname: "neofura"
#  database: "neofura"

database_test:
  host: "docker.for.mac.localhost"
  port: "27001"
  dbname: "Neo2"
  database: "Neo2"

database_local:
  host: "docker.for.mac.host.internal"
  port: "27004"
  dbname: "job"
  database: "job"

redis:
  host: "docker.for.mac.host.internal"
  port: "6379"

proxy:
  uri:
    - "http://seed1t4.neo.org:20332"
    - "http://seed2t4.neo.org:20332"
    - "http://seed3t4.neo.org:20332"
    - "http://seed4t4.neo.org:20332"
    - "http://seed5t4.neo.org:20332"

replica: "master"