

database_test:
  host: "docker.for.mac.localhost"
  port: "27001"
  dbname: "pChainDb3"
  database: "pChainDb3"

database_local:
  host: "docker.for.mac.host.internal"
  port: "27004"
  dbname: "job"
  database: "job"

redis:
  host: "docker.for.mac.host.internal"
  port: "6379"

proxy:
  uri:
    - "http://seed1t4.neo.org:20332"
    - "http://seed2t4.neo.org:20332"
    - "http://seed3t4.neo.org:20332"
    - "http://seed4t4.neo.org:20332"
    - "http://seed5t4.neo.org:20332"

replica: "master"